import Providers from '@/components/Providers';
import { cn } from '@/lib/utils';
import '@/styles/globals.css';
import { Inter as FontSans } from 'next/font/google';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-inter',
});

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html
      lang="en"
      className={cn('font-sans text-slate-900 antialiased', fontSans.variable)}
    >
      <head />
      <body className="min-h-screen">
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
